apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.backend.name }}
spec:
  selector:
    {{- include "myapp.backendLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.image.backend.port }}
    targetPort: {{ .Values.image.backend.port }}
  type: {{ .Values.service.type }}
