apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.backend.name }}
  labels:
    {{- include "myapp.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.backendLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "myapp.backendLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.backend.repository }}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: rds-secret-access
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret-access
              key: DB_PASSWORD
        - name: MYSQL_HOST
          value: {{ .Values.rds.host }}
        - name: MYSQL_DB
          value: {{ .Values.rds.name }}
        ports:
        - containerPort: 5001
