apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-external-access
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: tf-secretstore
    kind: SecretStore
  target:
    name: rds-secret-access
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: db-creds
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-creds
        property: DB_PASSWORD
