apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.frontend.name }}
spec:
  selector:
    {{- include "myapp.frontendLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.image.frontend.port }}
    targetPort: {{ .Values.image.frontend.port }}
  type: {{ .Values.service.type }}
