apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.frontend.name }}
  labels:
    {{- include "myapp.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.frontendLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "myapp.frontendLabels" . | nindent 8 }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.image.frontend.repository }}
        ports:
        - containerPort: 80
