apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-make-baby
  namespace: argocd
spec:
  project: default
  source:
    path: environment/dev
    repoURL: 'https://github.com/Virgin28/GitOps'
    targetRevision: main
    helm:
      valueFiles: 
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true