apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default
  sources:
    - path: 
      repoURL: "{{ .Values.global.chart.repo }}"
      targetRevision: "{{ .Values.global.chart.targetRevision }}"
      helm:
        valueFiles: 
          - $values/environments/{{ .Values.global.environment }}/values.yaml
    - repoURL: "{{ .Values.global.values.repo }}"
      targetRevision: "{{ .Values.global.values.targetRevision }}"
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
