name: GitHub Actions for Start-Doing

on:
  push:
    branches:
      - main
      - staging
      - dev
      - prod

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get the shortened commit SHA
        id: git-info
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Create ECR repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names gitops || aws ecr create-repository --repository-name gitops

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend (Python) image locally
        uses: docker/build-push-action@v5
        with:
          context: start-doing/backend
          file: start-doing/backend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: my-python-backend:latest

      - name: Build Frontend (NGINX) image locally
        uses: docker/build-push-action@v5
        with:
          context: start-doing/frontend
          file: start-doing/frontend/Dockerfile
          platforms: linux/amd64
          load: true
          tags: my-nginx-frontend:latest

      - name: Test network connectivity
        run: |
          # Start containers
          docker-compose -f start-doing/docker-compose.yaml up -d
          
          # Give containers time to start
          sleep 7
          
          # Install ping in frontend container (it might not have it by default)
          docker exec frontend apt-get update 
          docker exec frontend apt-get install -y iputils-ping
          
          # Simple ping test from frontend to backend
          echo "Testing network connectivity..."
          if ! docker exec frontend ping -c 2 backend; then
            echo "❌ Network connectivity test failed"
            docker-compose -f start-doing/docker-compose.yaml down
            exit 1
          fi
          
          echo "✅ Network connectivity test passed!"
          docker-compose -f start-doing/docker-compose.yaml down

      - name: Build and Push Backend (Python) multi-arch image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: start-doing/backend
          file: start-doing/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gitops:BACK-${{ env.sha }}

      - name: Build and Push Frontend (NGINX) multi-arch image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: start-doing/frontend
          file: start-doing/frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/gitops:FRONT-${{ env.sha }}
          
      - name: Login to GitHub
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
   
      - name: Clone GitOps Repository
        if: success()
        run: |
          cd /home/runner/work/
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Virgin28/GitOps-ArgoCD.git
          cd /home/runner/work/GitOps-ArgoCD
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Values File
        if: success()
        run: |
          cd /home/runner/work/GitOps-ArgoCD/environments/

          # Determine environment based on the branch name
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            env_dir="dev"
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            env_dir="staging"
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            env_dir="prod"
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            env_dir="dev"
          fi

          # Set the values file path
          values_file="$env_dir/values.yaml"

          # Debugging: Print out the values_file path
          echo "Using values file: $values_file"

          # Check if the values.yaml file exists
          if [[ ! -f "$values_file" ]]; then
            echo "❌ values.yaml not found at $values_file. Exiting."
            exit 1
          fi

          # Use the short SHA from the environment variable
          commit_sha="${{ env.sha }}"

          # Update values.yaml for frontend and backend with commit SHA tags
          sed -i "s|repository:.*gitops:FRONT-.*|repository: 058264364931.dkr.ecr.us-east-1.amazonaws.com/gitops:FRONT-${commit_sha}|g" $values_file
          sed -i "s|repository:.*gitops:BACK-.*|repository: 058264364931.dkr.ecr.us-east-1.amazonaws.com/gitops:BACK-${commit_sha}|g" $values_file

          # Debugging: Verify the changes were made
          echo "Updated values.yaml with frontend and backend commit SHA tags."

      - name: Commit and Push Changes
        if: success()
        run: |
          cd /home/runner/work/GitOps-ArgoCD/
          git add .
          git commit -m "Update image tags for ${{ github.ref_name }} to ${{ env.sha }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}